<x-forms.input
        :type="$type"
        :title="$title"
        :placeholder="$placeholder"
        :name="$name"
        :value="$value"
        :icon="$icon"
        :hint="$hint"
        :min="$min"
        :max="$max"
        :step="$step"
        :required="$required"
        :disabled="$disabled"
    />
